apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pricing-poc
namePrefix: pricing-

resources:
- ../../base

components:
  - ../../variants/prod
  - ../../variants/us-east-1

patchesStrategicMerge:
- deployment.yml
- version.yml
- replicas.yml
- settings.yml

images:
  - name: 534287151633.dkr.ecr.us-east-1.amazonaws.com/supply/pricing-poc
    newName: prodVersion.dkr.ecr.us-east-1.amazonaws.com/supply/pricing-poc