apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pricing-poc
namePrefix: pricing-

resources:
- ../../base

components:
- ../../variants/non-prod
- ../../variants/us-east-1

patches:
- path: deployment.yml
- path: version.yml
- path: replicas.yml
- path: settings.yml
