apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pricing-poc
namePrefix: pricing-

resources:
- ../../base

components:
- ../../variants/non-prod

patches:
- path: deployment.yml
- path: version.yml
- path: settings.yml
